### ISSUE TITLE
A couple of responsive layout issues

### ISSUE THREAD

**Issue by IonRutz** [MachoThemes/illdy#44]
Cuvintele lungi nu intra pe ecranele mici
ar fi ideal un line-height pe section titles
#34 intra la pachet :)

![image](https://cloud.githubusercontent.com/assets/15014267/18663687/37f26acc-7f28-11e6-9678-13a7d76b0714.png)
![image](https://cloud.githubusercontent.com/assets/15014267/18663649/08091aae-7f28-11e6-8cb0-66057ff3cf35.png)

**Comment by cristiantanase2016** [comment]
copiat pe repo'ul ildy https://github.com/puikinsh/illdy/issues/15
