### ISSUE TITLE
Add default widgets for w.org previewer

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/illdy#59]
https://github.com/MachoThemes/pixova-lite/blob/production/footer.php#L31-L39

Daca nu sunt pushi widgetzi de user in sidebar-urile din footer, hai sa hardcodam noi cativa ca sa arate preview-ul de pe w.org mai frumos.

Aceeasi treaba ar trebui facuta si pt. sidebar, ca momentan nu afiseaza toti widgetzii posibili (vezi
https://wordpress.org/themes/onepress/ )

**Comment by cristiantanase2016** [comment]
copiat pe repo'ul ildy https://github.com/puikinsh/illdy/issues/13
