### ISSUE TITLE
Add default images for blog posts

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/illdy#60]
Cream un folder inauntrul folder-ului temei cu 5-10 poze (o ping-uim pe Cristina sa ni le taie la dimensiunile la care ne trebuie). Aceste poze, vor fi folosite (random), pt. afisare ca si placeholder in cazul in care postarile de blog nu au featured image asociate :) Scopul principal e sa infrumusetam tot preview-ul de pe w.org

**Comment by cristiantanase2016** [comment]
copiat pe repo-ul ildy https://github.com/puikinsh/illdy/issues/12
