### ISSUE TITLE
Updating the theme => rebuilding the projects & testimonials section

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/illdy#63]
Good afternoon, and I hope this message finds you well. I'll start by saying that I know Illdy is a free theme, and that the amount of support available for a free theme is limited at best.

I am building a site for my client and noticed that, without any notice, all of my Services and Projects are gone. After searching the forums, I realized that the theme needed to be updated. I updated the theme and, while all of the Services an Projects are still missing, I am at least able to re-add them.

The problem is, this is a lot of work. And I don't mind doing it once. But if every time I update the site I need to rebuild the Services and Projects sections, this theme won't work for me or my client.

I did create an Illdy child theme – is this maybe the reason behind why I need to rebuild and recreate most of my homepage widgets? The site in question is not published, so I can't really direct you to it. I know that complicates your ability to help me.

Let me know if there is a way for me to update the theme without losing all of my hard work every time. I need to make a decision about whether or not I'll keep using the Illdy theme for my project.

Thanks.

**Comment by cristiantanase2016** [comment]
Bug posted on ildy repository
