### ISSUE TITLE
Missing translation from strings

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/illdy#64]
Check attachments.

I'm using Illdy theme and I found out few wrong localization words on it. I'm not sure if the language.pot file has those words missing or it's anything else.

I'm attaching screenshots that show it.

Read more on Latest news should be "Leia mais"
Comments on blog post header should be "Comentários"
Search on search widget should be "Pesquisar"

---

![comentarios](https://cloud.githubusercontent.com/assets/7841556/20430387/be94d842-ad9c-11e6-9bff-dbc5695e986c.png)
![readmore](https://cloud.githubusercontent.com/assets/7841556/20430389/be994350-ad9c-11e6-8da1-dff97a0f2eb9.png)
![searchbar](https://cloud.githubusercontent.com/assets/7841556/20430388/be990d2c-ad9c-11e6-8932-26621df2b359.png)

**Comment by cristiantanase2016** [comment]
Bug copied on ildy repository
